### PR TITLE
Fix crash in typechecker

### LINKED ISSUE #1264: Typechecker assertion failure on mismatched ranks
### What happened?

Not totally sure how this runs into the stablehlo codebase, but if I try to build an op like `mhlo.and(tensor<2xi1>,tensor<i1>)`, lldb backtrace gives me a crash at https://github.com/openxla/stablehlo/blob/52a9462f42c53795dbbf2c16c10e80db02221b94/stablehlo/dialect/Base.cpp#L315

It looks like we're iterating over the rank of the first argument without checking the rank of the second.

I'm not sure what the invariants of this function are supposed to be.

### PR DESCRIPTION
**Pull request by atondwal**
fixes #1264

### CODE REVIEW

**Comment by atondwal** [comment]
(Do we have negative tests for this sort of thing?)

File: stablehlo/dialect/Base.cpp [hunk 1]
```diff
@@ -300,6 +300,7 @@ FailureOr<TensorType> inferTypeWithCustomFn(
         Optional<Location>, int64_t, int64_t, int64_t, int64_t, int64_t)>
         inferDimAndBoundFn) {
   auto rank = rankedTypes[0].getRank();
+  if (rankedTypes[1].getRank() != rank) return failure();
```
Comment (sdasgup3) [inline stablehlo/dialect/Base.cpp:303]: Should we check for all  i `rankedTypes[i].getRank() != rank`

Comment (atondwal) [reply stablehlo/dialect/Base.cpp]: Yep.

File: stablehlo/dialect/Base.cpp [hunk 2]
```diff
@@ -300,6 +300,11 @@ FailureOr<TensorType> inferTypeWithCustomFn(
         Optional<Location>, int64_t, int64_t, int64_t, int64_t, int64_t)>
         inferDimAndBoundFn) {
   auto rank = rankedTypes[0].getRank();
+  for (auto& type : rankedTypes) {
+    if (type.getRank() != rank) {
+      return failure();
+    }
+  }
```
Comment (sdasgup3) [inline stablehlo/dialect/Base.cpp:307]: Thanks!
Can we use the loop below to add the check and on failure, return with a diagnostic message. Something like (feel free to use other messages)
```
  return emitOptionalError(location, "Mismatched ranks of types", rankedTypes[0].getRank(), " vs ", rankedTypes[i].getRank());
```

File: stablehlo/dialect/Base.cpp [hunk 3]
```diff
@@ -300,6 +300,13 @@ FailureOr<TensorType> inferTypeWithCustomFn(
         Optional<Location>, int64_t, int64_t, int64_t, int64_t, int64_t)>
         inferDimAndBoundFn) {
   auto rank = rankedTypes[0].getRank();
+  for (auto& type : rankedTypes) {
```
Comment (sdasgup3) [inline stablehlo/dialect/Base.cpp:303]: Checking for such assertions early  makes sense (as opposed to my earlier suggestion about merging with the for loop)

A trade-off  for more conciseness at the cost of slight less verbose messaging. Feel free to pass on to the next reviewer in case we disagree. 

```
  if (llvm::any_of(rankedTypes, [&](RankedTensorType type) {
        return rank != type.getRank();
      }))
    return emitOptionalError(location, "Expected input types to have same ranks");
```

**Review by sdasgup3 — APPROVED** [review]

File: stablehlo/dialect/Base.cpp (hunk 3 above)
Comment (atondwal) [reply stablehlo/dialect/Base.cpp:303]: I think printing the ranks is helpful for fault localization
